#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
# Copyright (C) 2024 Danil Lisin
# SPDX-License-Identifier: Apache-2.0

until mkdir "${config}/${user_id}_auth.lock" > /dev/null 2>&1
do
    sleep 1
done

. "${functions}/ib_auth"

rm -fr "${config}/${user_id}_auth.lock"
