#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
# Copyright (C) 2024 Danil Lisin
# SPDX-License-Identifier: Apache-2.0

set -- $(jq -r '.inline_query.query' "${update}")

if [ "${1}" = "null" ]
then
    exit 0
fi

command="${1}"

user_id="$(jq -r '.inline_query.from.id' "${update}")"
query_id="$(jq -r '.inline_query.id' "${update}")"
offset="$(jq -r '.inline_query.offset' "${update}")"

if [ -z "${command}" ]
then
    . "${submodules}/inline_none"
else
    shift
fi

case "${command}" in
    ("help")
        . "${submodules}/inline_help"
    ;;
    ("original")
        . "${submodules}/inline_original"
    ;;
    ("post")
        . "${submodules}/inline_post"
    ;;
    ("short")
        . "${submodules}/inline_short"
    ;;
    ("shorts" | s)
        . "${submodules}/inline_shorts"
    ;;
    (*)
        . "${submodules}/inline_search"
    ;;
esac

curl --data-urlencode "inline_query_id=${query_id}" \
    --data-urlencode "results=${results}" \
    --data-urlencode "cache_time=0" \
    --data-urlencode "next_offset=${next_offset}" \
    --get \
    --proxy "${internal}" \
    --silent \
    "${address}/bot${token}/answerInlineQuery" > /dev/null
