#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
# Copyright (C) 2024 Danil Lisin
# SPDX-License-Identifier: Apache-2.0

if [ -z "${1}" ]
then
    reply_text="$(jq -r '.message.reply_to_message.text' "${update}")"

    if [ "${reply_text}" = "null" ]
    then
        reply_text="$(jq -r '.message.reply_to_message.caption' "${update}")"
    fi

    if [ "${reply_text}" != "null" ]
    then
        ib_reply_name="$(printf "%s" "${reply_text}" | sed '1!d')"
        ib_post_id="$(printf "%s" "${reply_text}" | grep 'ID' | parameter 2)"

        for ib_board in ${ascii_table}
        do
            . "${units}/ib_config"

            if [ "${ib_reply_name}" = "${ib_name}" ]
            then
                break
            fi
        done

        set -- ${ib_board} ${ib_post_id}
    fi
fi

if [ -n "${1}" ]
then
    ib_board="${1}"
    ib_mode="p"

    . "${units}/ib_config"
    . "${units}/ib_authconfig"

    if [ -z "${ib_data_url}" ]
    then
        output_title="Invalid arguments"
        output_text="Unsupported image board"
        notification_text="${output_text}"

        return 0
    fi

    shift
else
    output_title="Invalid arguments"
    output_text="You must specify the image board"
    notification_text="${output_text}"

    return 0
fi

if [ -n "${1}" ]
then
    ib_post_id="${1}"
    shift
else
    output_title="Invalid arguments"
    output_text="You must specify the post ID"
    notification_text="${output_text}"

    return 0
fi

if [ -n "${ib_config}" ]
then
    . "${units}/ib_token"

    if [ -n "${output_text}" ]
    then
        notification_text="${output_title} ${output_text}"
        return 0
    fi
fi

if [ "${ib_name}" = "Idol Complex" ]
then
    ib_query="id_range:${ib_post_id}"
else
    ib_query="id:${ib_post_id}"
fi

ib_hash="$(printf "%s%s%s" "${user_id}" "${ib_board}" "${ib_post_id}" | enhash)"
. "${units}/ib_file"

if [ -n "${output_text}" ]
then
    notification_text="${output_text}"
fi
