#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
# Copyright (C) 2024 Danil Lisin
# SPDX-License-Identifier: Apache-2.0

output_text="$(echo "<b>Sekoohaka Bot v${version}</b>" \
    "\n\n<b>Fields descriptions:</b>" \
    "\n[command] - Inline command" \
    "\n[b] - Image board" \
    "\n[page] - Search page number" \
    "\n[options] - Search options" \
    "\n[name] - Search pool or tag name" \
    "\n[tags] - Search tags" \
    "\n[id] - Post ID" \
    "\n[query] - Inline query" \
    "\n[login] - Image board login or username" \
    "\n[key] - Image board API key or password" \
    "\n\n<b>Inline commands:</b>" \
    "\n<code>help</code> - Send this message" \
    "\n<code>l</code> [b] [page] [options] [name] - Pool search" \
    "\n<code>p</code> [b] [page] [options] [tags] - Post search" \
    "\n<code>t</code> [b] [page] [options] [name] - Tag search" \
    "\n<code>original</code> [b] [id] - Get original file of post" \
    "\n<code>post</code> [b] [id] - Get infromation of post" \
    "\n<code>short</code> [query] - Create inline shortcut" \
    "\n<code>shorts</code> - List saved inline shortcuts" \
    "\n\n<b>Search options:</b>" \
    "\na - Enable autopaging (lpt)" \
    "\nm - Show more metadata (p)" \
    "\np - Show gif/video as preview only (p)" \
    "\nq - Add quick buttons (lpt)" \
    "\n\n<b>Commands:</b>" \
    "\n/help - Send this message" \
    "\n/authorize [b] [login] [key] - Authorize to image board" \
    "\n/original [b] [id] - Get original file of post" \
    "\n/post [b] [id] - Get infromation of post" \
    "\n/short [query] - Create inline shortcut" \
    "\n/shorts - Manage saved shortcuts" \
    "\n/stop - Remove all your data" \
    "\n\n<b>Inline examples:</b>" \
    "\n<code>short p d -mq sakurada_shiro_(hy_plus)</code>" \
    "\n<code>original d 4507929</code>" \
    "\n<code>p d 1 -a ringouulu</code>" \
    "\n<code>t d *genshin*</code>" \
    "\n\n<b>Supported image boards:</b>")"

for ib_board in ${ascii_table}
do
    . "${submodules}/ib_config"
    . "${submodules}/ib_authconfig"

    if [ -n "${ib_name}" ]
    then
        output_text="$(printf '%s\n%c - <a href="%s">%s</a>' "${output_text}" "${ib_board}" "${ib_url}" "${ib_name}")"

        for ib_mode in ${ascii_table}
        do
            . "${submodules}/ib_config"

            if [ -n "${ib_data_url}" ]
            then
                ib_features="${ib_features}${ib_mode}"
            fi

            unset ib_data_url
        done

        if [ -n "${ib_config}" ]
        then
            output_text="$(printf "%s (auth)" "${output_text}")"
        fi

        if [ -n "${ib_features}" ]
        then
            output_text="$(printf "%s (%s)" "${output_text}" "${ib_features}")"
        fi
    fi

    unset ib_name ib_config ib_features
done
