#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
# Copyright (C) 2024 Danil Lisin
# SPDX-License-Identifier: Apache-2.0

if ! mkdir -p "${ib_config}"
then
    output_text="Failed to create user config"
    return 0
fi

if [ -n "${ib_login}" ]
then
    printf "%s" "${ib_login}" > "${ib_config}/${ib_login_file}"
fi

if [ -n "${ib_api_key}" ]
then
    printf "%s" "${ib_api_key}" > "${ib_config}/${ib_api_key_file}"
fi

if [ -f "${ib_config}/${ib_login_file}" ]
then
    ib_login="$(cat "${ib_config}/${ib_login_file}")"
else
    output_text="You must specify the ${ib_login_word}"
    return 0
fi

if [ -f "${ib_config}/${ib_api_key_file}" ]
then
    ib_api_key="$(cat "${ib_config}/${ib_api_key_file}")"
else
    output_text="You must specify the ${ib_api_key_word}"
    return 0
fi

case "${ib_board}" in
    (d)
        ib_file="${cache}/${update_id}_profile.json"

        if ! curl --max-time 5 \
            --output "${ib_file}" \
            --proxy "${proxy}" \
            --request GET \
            --silent \
            --user "${ib_login}:${ib_api_key}" \
            --user-agent "Sekoohaka" \
            "https://danbooru.donmai.us/profile.json"
        then
            output_text="Temporary error"
            return 0
        fi

        if ! [ -f "${ib_file}" ]
        then
            output_text="Failed to process request"
            return 0
        fi

        if ! jq -e '.' "${ib_file}" > /dev/null 2>&1
        then
            output_text="An unknown error occurred"
            return 0
        fi

        if [ "$(jq -r '.success' "${ib_file}")" = "false" ]
        then
            output_text="Error: <code>$(jq -r '.message' "${ib_file}" | htmlescape)</code>"
            return 0
        fi

        if [ "$(jq -r '.name' "${ib_file}")" != "${ib_login}" ]
        then
            output_text="An unexpected error occurred"
            return 0
        fi

        printf "%s" "${ib_login}:${ib_api_key}" | base64 > "${ib_config}/token"
    ;;
    (g)
        printf '%s="%s"\n%s="%s"' \
            "ib_dfield5" "user_id=${ib_login}" \
            "ib_dfield6" "api_key=${ib_api_key}" > "${ib_config}/legacy"
    ;;
    (i)
        ib_login_lower="$(printf "%s" "${ib_login}" | tr '[:upper:]' '[:lower:]')"
        ib_password_hash="$(printf "choujin-steiner--%s--" "${ib_api_key}" | sha1sum | cut -d ' ' -f 1)"
        ib_appkey="$(printf "sankakuapp_%s_Z5NE9YASej" "${ib_login_lower}" | sha1sum | cut -d ' ' -f 1)"

        printf '%s="%s"\n%s="%s"\n%s="%s"' \
            "ib_dfield4" "login=${ib_login}" \
            "ib_dfield5" "password_hash=${ib_password_hash}" \
            "ib_dfield6" "appkey=${ib_appkey}" > "${ib_config}/legacy"
    ;;
    (s)
        ib_login_data="$(jq --null-input --compact-output \
            --arg login "${ib_login}" \
            --arg password "${ib_api_key}" \
            '{"login": $login, "password": $password}')"

        ib_file="${cache}/${update_id}_token.json"

        if ! curl --data "${ib_login_data}" \
            --header "Content-Type: application/json" \
            --max-time 5 \
            --output "${ib_file}" \
            --proxy "${proxy}" \
            --request POST \
            --silent \
            --user-agent "Sekoohaka" \
            "https://capi-v2.sankakucomplex.com/auth/token"
        then
            output_text="Temporary error"
            return 0
        fi

        if ! [ -f "${ib_file}" ]
        then
            output_text="Failed to process request"
            return 0
        fi

        if ! jq -e '.' "${ib_file}" > /dev/null 2>&1
        then
            output_text="An unknown error occurred"
            return 0
        fi

        if [ "$(jq -r '.success' "${ib_file}")" != "true" ]
        then
            output_text="Error: <code>$(jq -r '.error' "${ib_file}" | htmlescape)</code>"
            return 0
        fi

        jq -r '.access_token' "${ib_file}" > "${ib_config}/token"
        date +%s > "${ib_config}/time"
    ;;
    (k | y)
        ib_file="${cache}/${update_id}_user.json"

        if ! curl --data-urlencode "username=${ib_login}" \
            --data-urlencode "api_key=${ib_api_key}" \
            --max-time 5 \
            --output "${ib_file}" \
            --proxy "${proxy}" \
            --silent \
            --user-agent "Sekoohaka" \
            "${ib_api}/user.json"
        then
            output_text="Temporary error"
            return 0
        fi

        if ! [ -f "${ib_file}" ]
        then
            output_text="Failed to process request"
            return 0
        fi

        if ! jq -e '.' "${ib_file}" > /dev/null 2>&1
        then
            output_text="Invalid username or API key"
            return 0
        fi

        printf '%s="%s"\n%s="%s"' \
            "ib_dfield5" "username=${ib_login}" \
            "ib_dfield6" "api_key=${ib_api_key}" > "${ib_config}/legacy"
    ;;
esac
