#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
# Copyright (C) 2024 Danil Lisin
# SPDX-License-Identifier: Apache-2.0

until mkdir "${config}/${ib_hash}.lock" > /dev/null 2>&1
do
    sleep 1
done

ib_file="${cache}/${ib_hash}.json"

if [ -f "${ib_file}" ]
then
    ib_mtime=$(stat -c %Y "${ib_file}")
    ib_ctime=$(date +%s)

    if [ $((ib_ctime - ib_mtime)) -gt 250 ]
    then
        rm -f "${ib_file}"
    fi
fi

if ! [ -f "${ib_file}" ]
then
    if ! curl --data-urlencode "${ib_dfield1}" \
        --data-urlencode "${ib_dfield2}" \
        --data-urlencode "${ib_dfield3}" \
        --data-urlencode "${ib_dfield4}" \
        --data-urlencode "${ib_dfield5}" \
        --data-urlencode "${ib_dfield6}" \
        --data-urlencode "${ib_dlimit}=${ib_limit}" \
        --data-urlencode "${ib_dpage}=$((ib_page + ib_ioffset))" \
        --data-urlencode "${ib_query}" \
        --get \
        --header "${ib_header}" \
        --max-time 5 \
        --output "${ib_file}" \
        --proxy "${proxy}" \
        --silent \
        --user-agent "Sekoohaka" \
        "${ib_data_url}"
    then
        output_text="Failed to access ${ib_name} API"
    fi

    if [ -z "${output_text}" ] && ! [ -f "${ib_file}" ]
    then
        output_text="Failed to access ${ib_name} API"
    fi

    if [ -n "${output_text}" ]
    then
        next_offset=${ib_page}
    fi

    if [ -z "${output_text}" ] && ! jq -e '.' "${ib_file}" > /dev/null 2>&1
    then
        output_text="An unknown error occurred"
    fi

    if [ -n "${output_text}" ]
    then
        output_title="An error occurred"
    fi

    if [ -z "${output_text}" ] && ! jq -e ".${ib_iarray}[0]|has(\"${ib_iid}\")" "${ib_file}" > /dev/null 2>&1
    then
        if [ -n "${inline_options}" ] && [ -n "${ib_offset}" ]
        then
            output_title="End of results"
        else
            output_title="No results found"
        fi

        if [ -n "${inline_options}" ]
        then
            case "${ib_mode}" in
                (l)
                    output_text="Try different page or pool name"
                ;;
                (p)
                    output_text="Try different page or tags"
                ;;
                (t)
                    output_text="Try different page or tag name"
                ;;
            esac
        else
            output_text="Try different post ID"
        fi
    fi

    if [ -n "${output_text}" ]
    then
        rm -f "${ib_file}"
    fi
fi

rm -fr "${config}/${ib_hash}.lock"
